pipeline {
    agent any

    
    stages {

        stage('Setup') {
            steps {
                sh "pip3 install -r 03-lambda-deployment/lambda-app/tests/requirements.txt"
            }
        }

        stage('Build') {
            steps {
                sh "sam build -t 03-lambda-deployment/lambda-app/template.yaml"

            }
        }
        stage('Deploy') {
            steps{
            withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                script{
                            sh 'aws sts get-caller-identity'
                            sh "sam deploy -t 03-lambda-deployment/lambda-app/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset"
                }
            }
      
            }
        }
    }
}
